<?php
require_once('template.header.php');
require_once('template.splash.php');
require_once('template.general.php');
require_once('template.services.php');
require_once('template.about.php');
require_once('template.contact.php');
require_once('template.footer.php');
?>